<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-25T11:29:34 IST" name="Suite" finished-at="2022-12-25T11:30:07 IST" duration-ms="33548">
    <groups>
    </groups>
    <test started-at="2022-12-25T11:29:34 IST" name="Test" finished-at="2022-12-25T11:30:07 IST" duration-ms="33548">
      <class name="TestCases.TC_using_DDT">
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.TC_using_DDT@27406a17]" started-at="2022-12-25T11:29:34 IST" name="setup" finished-at="2022-12-25T11:29:38 IST" duration-ms="4422" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyRegistrationAndLogin()[pri:-1, instance:TestCases.TC_using_DDT@27406a17]" started-at="2022-12-25T11:29:38 IST" name="verifyRegistrationAndLogin" finished-at="2022-12-25T11:29:48 IST" duration-ms="9492" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRegistrationAndLogin -->
        <test-method signature="VerifyLoginOfRegisteredCustomer(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.TC_using_DDT@27406a17]" started-at="2022-12-25T11:29:48 IST" name="VerifyLoginOfRegisteredCustomer" data-provider="LoginDataProvider" finished-at="2022-12-25T11:29:58 IST" duration-ms="9193" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[pravinjd@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[pravinjd@yahoo.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoginOfRegisteredCustomer -->
        <test-method signature="VerifyLoginOfRegisteredCustomer(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.TC_using_DDT@27406a17]" started-at="2022-12-25T11:29:58 IST" name="VerifyLoginOfRegisteredCustomer" data-provider="LoginDataProvider" finished-at="2022-12-25T11:30:07 IST" duration-ms="8995" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[pravin@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[pravin@yahoo.com]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.TC_using_DDT.VerifyLoginOfRegisteredCustomer(TC_using_DDT.java:158)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoginOfRegisteredCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.TC_using_DDT@27406a17]" started-at="2022-12-25T11:30:07 IST" name="tearDown" finished-at="2022-12-25T11:30:07 IST" duration-ms="596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.TC_using_DDT -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
